// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'a616477d2bfa7cc4f32bedcfd728aa4161e51ac5c610ffe603cfc27ac4aa7a2f'>;
export type ExecutionHash =
  ExecutionHashBase<'efbc1e60f192c8645e4a372146a84c7f56e02402c3446adae30e1f940443f322'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/float4@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/float8@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/int@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/int2@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/int4@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/int8@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/int8number@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/interval@1': {
        readonly output: 'pg/interval@1';
        readonly nullable: true;
      };
      readonly 'pg/numeric@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/time-string@1': {
        readonly output: 'pg/interval@1';
        readonly nullable: true;
      };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/interval@1';
        readonly nullable: true;
      };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/int2@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/int4@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/int8@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/int8number@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/numeric@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: {
      readonly output: 'pg/int8number@1';
      readonly nullable: false;
    };
    readonly anyInput: {
      readonly output: 'pg/int8number@1';
      readonly nullable: false;
    };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: {
      readonly output: 'pg/int8@1';
      readonly nullable: false;
    };
    readonly anyInput: {
      readonly output: 'pg/int8@1';
      readonly nullable: false;
    };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': {
        readonly output: 'pg/char@1';
        readonly nullable: true;
      };
      readonly 'pg/date-string@1': {
        readonly output: 'pg/date-string@1';
        readonly nullable: true;
      };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': {
        readonly output: 'pg/enum@1';
        readonly nullable: true;
      };
      readonly 'pg/float@1': {
        readonly output: 'pg/float@1';
        readonly nullable: true;
      };
      readonly 'pg/float4@1': {
        readonly output: 'pg/float4@1';
        readonly nullable: true;
      };
      readonly 'pg/float8@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/inet@1': {
        readonly output: 'pg/inet@1';
        readonly nullable: true;
      };
      readonly 'pg/int@1': {
        readonly output: 'pg/int@1';
        readonly nullable: true;
      };
      readonly 'pg/int2@1': {
        readonly output: 'pg/int2@1';
        readonly nullable: true;
      };
      readonly 'pg/int4@1': {
        readonly output: 'pg/int4@1';
        readonly nullable: true;
      };
      readonly 'pg/int8@1': {
        readonly output: 'pg/int8@1';
        readonly nullable: true;
      };
      readonly 'pg/int8number@1': {
        readonly output: 'pg/int8number@1';
        readonly nullable: true;
      };
      readonly 'pg/interval@1': {
        readonly output: 'pg/interval@1';
        readonly nullable: true;
      };
      readonly 'pg/numeric@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/text-array@1': {
        readonly output: 'pg/text-array@1';
        readonly nullable: true;
      };
      readonly 'pg/text@1': {
        readonly output: 'pg/text@1';
        readonly nullable: true;
      };
      readonly 'pg/time-string@1': {
        readonly output: 'pg/time-string@1';
        readonly nullable: true;
      };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': {
        readonly output: 'pg/timetz@1';
        readonly nullable: true;
      };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': {
        readonly output: 'pg/text@1';
        readonly nullable: true;
      };
      readonly 'sql/char@1': {
        readonly output: 'sql/char@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': {
        readonly output: 'sql/float@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': {
        readonly output: 'sql/int@1';
        readonly nullable: true;
      };
      readonly 'sql/text@1': {
        readonly output: 'sql/text@1';
        readonly nullable: true;
      };
      readonly 'sql/varchar@1': {
        readonly output: 'pg/text@1';
        readonly nullable: true;
      };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': {
        readonly output: 'pg/char@1';
        readonly nullable: true;
      };
      readonly 'pg/date-string@1': {
        readonly output: 'pg/date-string@1';
        readonly nullable: true;
      };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': {
        readonly output: 'pg/enum@1';
        readonly nullable: true;
      };
      readonly 'pg/float@1': {
        readonly output: 'pg/float@1';
        readonly nullable: true;
      };
      readonly 'pg/float4@1': {
        readonly output: 'pg/float4@1';
        readonly nullable: true;
      };
      readonly 'pg/float8@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/inet@1': {
        readonly output: 'pg/inet@1';
        readonly nullable: true;
      };
      readonly 'pg/int@1': {
        readonly output: 'pg/int@1';
        readonly nullable: true;
      };
      readonly 'pg/int2@1': {
        readonly output: 'pg/int2@1';
        readonly nullable: true;
      };
      readonly 'pg/int4@1': {
        readonly output: 'pg/int4@1';
        readonly nullable: true;
      };
      readonly 'pg/int8@1': {
        readonly output: 'pg/int8@1';
        readonly nullable: true;
      };
      readonly 'pg/int8number@1': {
        readonly output: 'pg/int8number@1';
        readonly nullable: true;
      };
      readonly 'pg/interval@1': {
        readonly output: 'pg/interval@1';
        readonly nullable: true;
      };
      readonly 'pg/numeric@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/text-array@1': {
        readonly output: 'pg/text-array@1';
        readonly nullable: true;
      };
      readonly 'pg/text@1': {
        readonly output: 'pg/text@1';
        readonly nullable: true;
      };
      readonly 'pg/time-string@1': {
        readonly output: 'pg/time-string@1';
        readonly nullable: true;
      };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': {
        readonly output: 'pg/timetz@1';
        readonly nullable: true;
      };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': {
        readonly output: 'pg/text@1';
        readonly nullable: true;
      };
      readonly 'sql/char@1': {
        readonly output: 'sql/char@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': {
        readonly output: 'sql/float@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': {
        readonly output: 'sql/int@1';
        readonly nullable: true;
      };
      readonly 'sql/text@1': {
        readonly output: 'sql/text@1';
        readonly nullable: true;
      };
      readonly 'sql/varchar@1': {
        readonly output: 'pg/text@1';
        readonly nullable: true;
      };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/float4@1': {
        readonly output: 'pg/float4@1';
        readonly nullable: true;
      };
      readonly 'pg/float8@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/int@1': {
        readonly output: 'pg/int8number@1';
        readonly nullable: true;
      };
      readonly 'pg/int2@1': {
        readonly output: 'pg/int8number@1';
        readonly nullable: true;
      };
      readonly 'pg/int4@1': {
        readonly output: 'pg/int8number@1';
        readonly nullable: true;
      };
      readonly 'pg/int8@1': {
        readonly output: 'pg/int8number@1';
        readonly nullable: true;
      };
      readonly 'pg/int8number@1': {
        readonly output: 'pg/int8number@1';
        readonly nullable: true;
      };
      readonly 'pg/interval@1': {
        readonly output: 'pg/interval@1';
        readonly nullable: true;
      };
      readonly 'pg/numeric@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/time-string@1': {
        readonly output: 'pg/interval@1';
        readonly nullable: true;
      };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/interval@1';
        readonly nullable: true;
      };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': {
        readonly output: 'pg/int8number@1';
        readonly nullable: true;
      };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': {
        readonly output: 'pg/int8@1';
        readonly nullable: true;
      };
      readonly 'pg/int2@1': {
        readonly output: 'pg/int8@1';
        readonly nullable: true;
      };
      readonly 'pg/int4@1': {
        readonly output: 'pg/int8@1';
        readonly nullable: true;
      };
      readonly 'pg/int8@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/int8number@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': {
        readonly output: 'pg/int8@1';
        readonly nullable: true;
      };
    };
  };
};
type DefaultLiteralValue<
  CodecId extends string,
  Encoded,
> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Airline: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
    };
    readonly Booking: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly userId: CodecTypes['pg/text@1']['output'];
      readonly status:
        | 'in_progress'
        | 'awaiting_user_decision'
        | 'partially_confirmed'
        | 'confirmed'
        | 'failed';
      readonly decisionExpiresAt:
        CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly BookingStep: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly bookingId: CodecTypes['pg/text@1']['output'];
      readonly flightBookingId: CodecTypes['pg/text@1']['output'] | null;
      readonly hotelBookingId: CodecTypes['pg/text@1']['output'] | null;
      readonly stepIndex: CodecTypes['pg/int4@1']['output'];
      readonly stage: CodecTypes['pg/int4@1']['output'];
      readonly stepName: CodecTypes['pg/text@1']['output'];
      readonly scope: 'product' | 'itinerary';
      readonly agent: CodecTypes['pg/text@1']['output'];
      readonly status:
        | 'pending'
        | 'in_progress'
        | 'success'
        | 'failed'
        | 'compensating'
        | 'compensated';
      readonly attempt: CodecTypes['pg/int4@1']['output'];
      readonly retryable: CodecTypes['pg/bool@1']['output'] | null;
      readonly result: CodecTypes['pg/json@1']['output'] | null;
      readonly error: CodecTypes['pg/json@1']['output'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly Flight: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly airlineId: CodecTypes['pg/text@1']['output'];
      readonly flightNumber: CodecTypes['pg/text@1']['output'];
      readonly origin: CodecTypes['pg/text@1']['output'];
      readonly destination: CodecTypes['pg/text@1']['output'];
      readonly departureTime: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly price: CodecTypes['pg/numeric@1']['output'];
      readonly seatsLeft: CodecTypes['pg/int4@1']['output'];
    };
    readonly FlightBooking: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly bookingId: CodecTypes['pg/text@1']['output'];
      readonly flightId: CodecTypes['pg/text@1']['output'];
      readonly flightNumber: CodecTypes['pg/text@1']['output'] | null;
      readonly origin: CodecTypes['pg/text@1']['output'];
      readonly destination: CodecTypes['pg/text@1']['output'];
      readonly departureDate: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly passengers: CodecTypes['pg/int4@1']['output'];
    };
    readonly FraudBlacklist: {
      readonly userId: CodecTypes['pg/text@1']['output'];
    };
    readonly Hotel: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly city: CodecTypes['pg/text@1']['output'];
    };
    readonly HotelBooking: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly bookingId: CodecTypes['pg/text@1']['output'];
      readonly hotelId: CodecTypes['pg/text@1']['output'];
      readonly hotelName: CodecTypes['pg/text@1']['output'] | null;
      readonly roomId: CodecTypes['pg/text@1']['output'] | null;
      readonly roomType: CodecTypes['pg/text@1']['output'] | null;
      readonly city: CodecTypes['pg/text@1']['output'];
      readonly checkIn: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly checkOut: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly rooms: CodecTypes['pg/int4@1']['output'];
    };
    readonly Room: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly hotelId: CodecTypes['pg/text@1']['output'];
      readonly roomType: CodecTypes['pg/text@1']['output'];
      readonly price: CodecTypes['pg/numeric@1']['output'];
      readonly available: CodecTypes['pg/bool@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Airline: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
    };
    readonly Booking: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly userId: CodecTypes['pg/text@1']['input'];
      readonly status:
        | 'in_progress'
        | 'awaiting_user_decision'
        | 'partially_confirmed'
        | 'confirmed'
        | 'failed';
      readonly decisionExpiresAt:
        CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly BookingStep: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly bookingId: CodecTypes['pg/text@1']['input'];
      readonly flightBookingId: CodecTypes['pg/text@1']['input'] | null;
      readonly hotelBookingId: CodecTypes['pg/text@1']['input'] | null;
      readonly stepIndex: CodecTypes['pg/int4@1']['input'];
      readonly stage: CodecTypes['pg/int4@1']['input'];
      readonly stepName: CodecTypes['pg/text@1']['input'];
      readonly scope: 'product' | 'itinerary';
      readonly agent: CodecTypes['pg/text@1']['input'];
      readonly status:
        | 'pending'
        | 'in_progress'
        | 'success'
        | 'failed'
        | 'compensating'
        | 'compensated';
      readonly attempt: CodecTypes['pg/int4@1']['input'];
      readonly retryable: CodecTypes['pg/bool@1']['input'] | null;
      readonly result: CodecTypes['pg/json@1']['input'] | null;
      readonly error: CodecTypes['pg/json@1']['input'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly Flight: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly airlineId: CodecTypes['pg/text@1']['input'];
      readonly flightNumber: CodecTypes['pg/text@1']['input'];
      readonly origin: CodecTypes['pg/text@1']['input'];
      readonly destination: CodecTypes['pg/text@1']['input'];
      readonly departureTime: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly price: CodecTypes['pg/numeric@1']['input'];
      readonly seatsLeft: CodecTypes['pg/int4@1']['input'];
    };
    readonly FlightBooking: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly bookingId: CodecTypes['pg/text@1']['input'];
      readonly flightId: CodecTypes['pg/text@1']['input'];
      readonly flightNumber: CodecTypes['pg/text@1']['input'] | null;
      readonly origin: CodecTypes['pg/text@1']['input'];
      readonly destination: CodecTypes['pg/text@1']['input'];
      readonly departureDate: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly passengers: CodecTypes['pg/int4@1']['input'];
    };
    readonly FraudBlacklist: {
      readonly userId: CodecTypes['pg/text@1']['input'];
    };
    readonly Hotel: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly city: CodecTypes['pg/text@1']['input'];
    };
    readonly HotelBooking: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly bookingId: CodecTypes['pg/text@1']['input'];
      readonly hotelId: CodecTypes['pg/text@1']['input'];
      readonly hotelName: CodecTypes['pg/text@1']['input'] | null;
      readonly roomId: CodecTypes['pg/text@1']['input'] | null;
      readonly roomType: CodecTypes['pg/text@1']['input'] | null;
      readonly city: CodecTypes['pg/text@1']['input'];
      readonly checkIn: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly checkOut: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly rooms: CodecTypes['pg/int4@1']['input'];
    };
    readonly Room: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly hotelId: CodecTypes['pg/text@1']['input'];
      readonly roomType: CodecTypes['pg/text@1']['input'];
      readonly price: CodecTypes['pg/numeric@1']['input'];
      readonly available: CodecTypes['pg/bool@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly airline: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
    };
    readonly booking: {
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly decision_expires_at:
        CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly status:
        | 'in_progress'
        | 'awaiting_user_decision'
        | 'partially_confirmed'
        | 'confirmed'
        | 'failed';
      readonly updated_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly user_id: CodecTypes['pg/text@1']['output'];
    };
    readonly booking_step: {
      readonly agent: CodecTypes['pg/text@1']['output'];
      readonly attempt: CodecTypes['pg/int4@1']['output'];
      readonly booking_id: CodecTypes['pg/text@1']['output'];
      readonly error: CodecTypes['pg/json@1']['output'] | null;
      readonly flight_booking_id: CodecTypes['pg/text@1']['output'] | null;
      readonly hotel_booking_id: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly result: CodecTypes['pg/json@1']['output'] | null;
      readonly retryable: CodecTypes['pg/bool@1']['output'] | null;
      readonly scope: 'product' | 'itinerary';
      readonly stage: CodecTypes['pg/int4@1']['output'];
      readonly status:
        | 'pending'
        | 'in_progress'
        | 'success'
        | 'failed'
        | 'compensating'
        | 'compensated';
      readonly step_index: CodecTypes['pg/int4@1']['output'];
      readonly step_name: CodecTypes['pg/text@1']['output'];
      readonly updated_at: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly flight: {
      readonly airline_id: CodecTypes['pg/text@1']['output'];
      readonly departure_time: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly destination: CodecTypes['pg/text@1']['output'];
      readonly flight_number: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly origin: CodecTypes['pg/text@1']['output'];
      readonly price: CodecTypes['pg/numeric@1']['output'];
      readonly seats_left: CodecTypes['pg/int4@1']['output'];
    };
    readonly flight_booking: {
      readonly booking_id: CodecTypes['pg/text@1']['output'];
      readonly departure_date: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly destination: CodecTypes['pg/text@1']['output'];
      readonly flight_id: CodecTypes['pg/text@1']['output'];
      readonly flight_number: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly origin: CodecTypes['pg/text@1']['output'];
      readonly passengers: CodecTypes['pg/int4@1']['output'];
    };
    readonly fraud_blacklist: {
      readonly user_id: CodecTypes['pg/text@1']['output'];
    };
    readonly hotel: {
      readonly city: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
    };
    readonly hotel_booking: {
      readonly booking_id: CodecTypes['pg/text@1']['output'];
      readonly check_in: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly check_out: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly city: CodecTypes['pg/text@1']['output'];
      readonly hotel_id: CodecTypes['pg/text@1']['output'];
      readonly hotel_name: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly room_id: CodecTypes['pg/text@1']['output'] | null;
      readonly room_type: CodecTypes['pg/text@1']['output'] | null;
      readonly rooms: CodecTypes['pg/int4@1']['output'];
    };
    readonly room: {
      readonly available: CodecTypes['pg/bool@1']['output'];
      readonly hotel_id: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly price: CodecTypes['pg/numeric@1']['output'];
      readonly room_type: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly airline: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
    };
    readonly booking: {
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly decision_expires_at:
        CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly status:
        | 'in_progress'
        | 'awaiting_user_decision'
        | 'partially_confirmed'
        | 'confirmed'
        | 'failed';
      readonly updated_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly user_id: CodecTypes['pg/text@1']['input'];
    };
    readonly booking_step: {
      readonly agent: CodecTypes['pg/text@1']['input'];
      readonly attempt: CodecTypes['pg/int4@1']['input'];
      readonly booking_id: CodecTypes['pg/text@1']['input'];
      readonly error: CodecTypes['pg/json@1']['input'] | null;
      readonly flight_booking_id: CodecTypes['pg/text@1']['input'] | null;
      readonly hotel_booking_id: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly result: CodecTypes['pg/json@1']['input'] | null;
      readonly retryable: CodecTypes['pg/bool@1']['input'] | null;
      readonly scope: 'product' | 'itinerary';
      readonly stage: CodecTypes['pg/int4@1']['input'];
      readonly status:
        | 'pending'
        | 'in_progress'
        | 'success'
        | 'failed'
        | 'compensating'
        | 'compensated';
      readonly step_index: CodecTypes['pg/int4@1']['input'];
      readonly step_name: CodecTypes['pg/text@1']['input'];
      readonly updated_at: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly flight: {
      readonly airline_id: CodecTypes['pg/text@1']['input'];
      readonly departure_time: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly destination: CodecTypes['pg/text@1']['input'];
      readonly flight_number: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly origin: CodecTypes['pg/text@1']['input'];
      readonly price: CodecTypes['pg/numeric@1']['input'];
      readonly seats_left: CodecTypes['pg/int4@1']['input'];
    };
    readonly flight_booking: {
      readonly booking_id: CodecTypes['pg/text@1']['input'];
      readonly departure_date: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly destination: CodecTypes['pg/text@1']['input'];
      readonly flight_id: CodecTypes['pg/text@1']['input'];
      readonly flight_number: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly origin: CodecTypes['pg/text@1']['input'];
      readonly passengers: CodecTypes['pg/int4@1']['input'];
    };
    readonly fraud_blacklist: {
      readonly user_id: CodecTypes['pg/text@1']['input'];
    };
    readonly hotel: {
      readonly city: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
    };
    readonly hotel_booking: {
      readonly booking_id: CodecTypes['pg/text@1']['input'];
      readonly check_in: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly check_out: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly city: CodecTypes['pg/text@1']['input'];
      readonly hotel_id: CodecTypes['pg/text@1']['input'];
      readonly hotel_name: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly room_id: CodecTypes['pg/text@1']['input'] | null;
      readonly room_type: CodecTypes['pg/text@1']['input'] | null;
      readonly rooms: CodecTypes['pg/int4@1']['input'];
    };
    readonly room: {
      readonly available: CodecTypes['pg/bool@1']['input'];
      readonly hotel_id: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly price: CodecTypes['pg/numeric@1']['input'];
      readonly room_type: CodecTypes['pg/text@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly airline: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly booking: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly user_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<
                      'pg/text@1',
                      'in_progress'
                    >;
                  };
                };
                readonly decision_expires_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: true;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'now()';
                  };
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly booking_step: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly booking_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly flight_booking_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly hotel_booking_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly step_index: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly stage: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly step_name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly scope: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly agent: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'pending'>;
                  };
                };
                readonly attempt: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly retryable: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: true;
                };
                readonly result: {
                  readonly nativeType: 'json';
                  readonly codecId: 'pg/json@1';
                  readonly nullable: true;
                };
                readonly error: {
                  readonly nativeType: 'json';
                  readonly codecId: 'pg/json@1';
                  readonly nullable: true;
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'booking_step_booking_id_idx_aeea169b';
                  readonly prefix: 'booking_step_booking_id_idx';
                  readonly columns: readonly ['booking_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'booking_step_flight_booking_id_idx_3c0ff35c';
                  readonly prefix: 'booking_step_flight_booking_id_idx';
                  readonly columns: readonly ['flight_booking_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'booking_step_hotel_booking_id_idx_57ba87aa';
                  readonly prefix: 'booking_step_hotel_booking_id_idx';
                  readonly columns: readonly ['hotel_booking_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'booking_step_status_idx_e98638ab';
                  readonly prefix: 'booking_step_status_idx';
                  readonly columns: readonly ['status'];
                  readonly unique: false;
                },
                {
                  readonly name: 'booking_step_booking_id_stage_idx_90ddef17';
                  readonly prefix: 'booking_step_booking_id_stage_idx';
                  readonly columns: readonly ['booking_id', 'stage'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'booking_step';
                    readonly columns: readonly ['booking_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'booking';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'booking_step';
                    readonly columns: readonly ['flight_booking_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'flight_booking';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'booking_step';
                    readonly columns: readonly ['hotel_booking_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'hotel_booking';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly flight: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly airline_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly flight_number: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly origin: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly destination: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly departure_time: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
                readonly price: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
                readonly seats_left: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'flight_airline_id_idx_1844ec6e';
                  readonly prefix: 'flight_airline_id_idx';
                  readonly columns: readonly ['airline_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'flight';
                    readonly columns: readonly ['airline_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'airline';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly flight_booking: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly booking_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly flight_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly flight_number: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly origin: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly destination: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly departure_date: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
                readonly passengers: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 1>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'flight_booking_booking_id_idx_aeea169b';
                  readonly prefix: 'flight_booking_booking_id_idx';
                  readonly columns: readonly ['booking_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'flight_booking';
                    readonly columns: readonly ['booking_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'booking';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly fraud_blacklist: {
              columns: {
                readonly user_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['user_id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly hotel: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly city: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly hotel_booking: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly booking_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly hotel_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly hotel_name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly room_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly room_type: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly city: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly check_in: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
                readonly check_out: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
                readonly rooms: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 1>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'hotel_booking_booking_id_idx_aeea169b';
                  readonly prefix: 'hotel_booking_booking_id_idx';
                  readonly columns: readonly ['booking_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'hotel_booking';
                    readonly columns: readonly ['booking_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'booking';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly room: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly hotel_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly room_type: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly price: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
                readonly available: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'room_hotel_id_idx_3d513303';
                  readonly prefix: 'room_hotel_id_idx';
                  readonly columns: readonly ['hotel_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'room';
                    readonly columns: readonly ['hotel_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'hotel';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
          };
          readonly valueSet: {
            readonly BookingStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly [
                'in_progress',
                'awaiting_user_decision',
                'partially_confirmed',
                'confirmed',
                'failed',
              ];
            };
            readonly StepScope: {
              readonly kind: 'valueSet';
              readonly values: readonly ['product', 'itinerary'];
            };
            readonly StepStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly [
                'pending',
                'in_progress',
                'success',
                'failed',
                'compensating',
                'compensated',
              ];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly booking: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Booking';
    };
    readonly flight_booking: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'FlightBooking';
    };
    readonly hotel_booking: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'HotelBooking';
    };
    readonly booking_step: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'BookingStep';
    };
    readonly hotel: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Hotel';
    };
    readonly room: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Room';
    };
    readonly airline: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Airline';
    };
    readonly flight: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Flight';
    };
    readonly fraud_blacklist: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'FraudBlacklist';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Airline: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
            };
            readonly relations: {
              readonly flights: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Flight';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['airlineId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'airline';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
              };
            };
          };
          readonly Booking: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly decisionExpiresAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly flightBookings: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'FlightBooking';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['bookingId'];
                };
              };
              readonly hotelBookings: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'HotelBooking';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['bookingId'];
                };
              };
              readonly steps: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'BookingStep';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['bookingId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'booking';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly userId: { readonly column: 'user_id' };
                readonly status: { readonly column: 'status' };
                readonly decisionExpiresAt: {
                  readonly column: 'decision_expires_at';
                };
                readonly createdAt: { readonly column: 'created_at' };
                readonly updatedAt: { readonly column: 'updated_at' };
              };
            };
          };
          readonly BookingStep: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly bookingId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly flightBookingId: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly hotelBookingId: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly stepIndex: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/int4@1';
                };
              };
              readonly stage: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/int4@1';
                };
              };
              readonly stepName: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly scope: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly agent: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly attempt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/int4@1';
                };
              };
              readonly retryable: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/bool@1';
                };
              };
              readonly result: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/json@1';
                };
              };
              readonly error: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/json@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly booking: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Booking';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['bookingId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly flightBooking: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'FlightBooking';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['flightBookingId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly hotelBooking: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'HotelBooking';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['hotelBookingId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'booking_step';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly bookingId: { readonly column: 'booking_id' };
                readonly flightBookingId: {
                  readonly column: 'flight_booking_id';
                };
                readonly hotelBookingId: {
                  readonly column: 'hotel_booking_id';
                };
                readonly stepIndex: { readonly column: 'step_index' };
                readonly stage: { readonly column: 'stage' };
                readonly stepName: { readonly column: 'step_name' };
                readonly scope: { readonly column: 'scope' };
                readonly agent: { readonly column: 'agent' };
                readonly status: { readonly column: 'status' };
                readonly attempt: { readonly column: 'attempt' };
                readonly retryable: { readonly column: 'retryable' };
                readonly result: { readonly column: 'result' };
                readonly error: { readonly column: 'error' };
                readonly updatedAt: { readonly column: 'updated_at' };
              };
            };
          };
          readonly Flight: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly airlineId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly flightNumber: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly origin: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly destination: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly departureTime: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly price: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/numeric@1';
                };
              };
              readonly seatsLeft: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/int4@1';
                };
              };
            };
            readonly relations: {
              readonly airline: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Airline';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['airlineId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'flight';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly airlineId: { readonly column: 'airline_id' };
                readonly flightNumber: { readonly column: 'flight_number' };
                readonly origin: { readonly column: 'origin' };
                readonly destination: { readonly column: 'destination' };
                readonly departureTime: { readonly column: 'departure_time' };
                readonly price: { readonly column: 'price' };
                readonly seatsLeft: { readonly column: 'seats_left' };
              };
            };
          };
          readonly FlightBooking: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly bookingId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly flightId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly flightNumber: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly origin: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly destination: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly departureDate: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly passengers: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/int4@1';
                };
              };
            };
            readonly relations: {
              readonly booking: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Booking';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['bookingId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly steps: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'BookingStep';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['flightBookingId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'flight_booking';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly bookingId: { readonly column: 'booking_id' };
                readonly flightId: { readonly column: 'flight_id' };
                readonly flightNumber: { readonly column: 'flight_number' };
                readonly origin: { readonly column: 'origin' };
                readonly destination: { readonly column: 'destination' };
                readonly departureDate: { readonly column: 'departure_date' };
                readonly passengers: { readonly column: 'passengers' };
              };
            };
          };
          readonly FraudBlacklist: {
            readonly fields: {
              readonly userId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'fraud_blacklist';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly userId: { readonly column: 'user_id' };
              };
            };
          };
          readonly Hotel: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly city: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
            };
            readonly relations: {
              readonly rooms: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Room';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['hotelId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'hotel';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly city: { readonly column: 'city' };
              };
            };
          };
          readonly HotelBooking: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly bookingId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly hotelId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly hotelName: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly roomId: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly roomType: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly city: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly checkIn: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly checkOut: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly rooms: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/int4@1';
                };
              };
            };
            readonly relations: {
              readonly booking: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Booking';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['bookingId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly steps: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'BookingStep';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['hotelBookingId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'hotel_booking';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly bookingId: { readonly column: 'booking_id' };
                readonly hotelId: { readonly column: 'hotel_id' };
                readonly hotelName: { readonly column: 'hotel_name' };
                readonly roomId: { readonly column: 'room_id' };
                readonly roomType: { readonly column: 'room_type' };
                readonly city: { readonly column: 'city' };
                readonly checkIn: { readonly column: 'check_in' };
                readonly checkOut: { readonly column: 'check_out' };
                readonly rooms: { readonly column: 'rooms' };
              };
            };
          };
          readonly Room: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly hotelId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly roomType: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly price: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/numeric@1';
                };
              };
              readonly available: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/bool@1';
                };
              };
            };
            readonly relations: {
              readonly hotel: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Hotel';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['hotelId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'room';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly hotelId: { readonly column: 'hotel_id' };
                readonly roomType: { readonly column: 'room_type' };
                readonly price: { readonly column: 'price' };
                readonly available: { readonly column: 'available' };
              };
            };
          };
        };
        readonly enum: {
          readonly BookingStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'in_progress'; readonly value: 'in_progress' },
              {
                readonly name: 'awaiting_user_decision';
                readonly value: 'awaiting_user_decision';
              },
              {
                readonly name: 'partially_confirmed';
                readonly value: 'partially_confirmed';
              },
              { readonly name: 'confirmed'; readonly value: 'confirmed' },
              { readonly name: 'failed'; readonly value: 'failed' },
            ];
          };
          readonly StepScope: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'product'; readonly value: 'product' },
              { readonly name: 'itinerary'; readonly value: 'itinerary' },
            ];
          };
          readonly StepStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'pending'; readonly value: 'pending' },
              { readonly name: 'in_progress'; readonly value: 'in_progress' },
              { readonly name: 'success'; readonly value: 'success' },
              { readonly name: 'failed'; readonly value: 'failed' },
              { readonly name: 'compensating'; readonly value: 'compensating' },
              { readonly name: 'compensated'; readonly value: 'compensated' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'booking';
            readonly column: 'id';
          };
          readonly onCreate: {
            readonly kind: 'generator';
            readonly id: 'uuidv4';
          };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'booking';
            readonly column: 'updated_at';
          };
          readonly onCreate: {
            readonly kind: 'generator';
            readonly id: 'timestampNow';
          };
          readonly onUpdate: {
            readonly kind: 'generator';
            readonly id: 'timestampNow';
          };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'booking_step';
            readonly column: 'id';
          };
          readonly onCreate: {
            readonly kind: 'generator';
            readonly id: 'uuidv4';
          };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'booking_step';
            readonly column: 'updated_at';
          };
          readonly onCreate: {
            readonly kind: 'generator';
            readonly id: 'timestampNow';
          };
          readonly onUpdate: {
            readonly kind: 'generator';
            readonly id: 'timestampNow';
          };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'flight_booking';
            readonly column: 'id';
          };
          readonly onCreate: {
            readonly kind: 'generator';
            readonly id: 'uuidv4';
          };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'hotel_booking';
            readonly column: 'id';
          };
          readonly onCreate: {
            readonly kind: 'generator';
            readonly id: 'uuidv4';
          };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
